<?xml version="1.0" encoding="UTF-8"?>
<SCL revision="B" version="2007" xmlns="http://www.iec.ch/61850/2003/SCL" >
  <Header id=""/>
  <Substation name="substation">
  	<VoltageLevel name="voltageLevel1" numPhases="0">
  	  <Bay name="bay">
  	  </Bay>
  	</VoltageLevel>
  	<VoltageLevel name="voltageLevel2" numPhases="1000">
  	  <Bay name="bay">
  	  </Bay>
  	</VoltageLevel>
  </Substation>
</SCL>
